### ISSUE TITLE
Acknowledgment: Thank you

### ISSUE THREAD

**Issue by ryukinix** [ksxelectronapps/lichess-app#1]
Thanks for generating this and as well the package for Arch Linux as release. This is a grateful practice.

**Comment by KSXGitHub** [comment]
You're welcome. :smile: 

I created this repo long time ago for learning purpose (I learn electron-builder). Now that I'm done, this project is left unmaintained, I'll be glad if someone willing to take my place and develop it further.

**Comment by KSXGitHub** [comment]
BTW, how do you find this repo? (Just curious)

**Comment by ryukinix** [comment]
I was really looking of a desktop linux app for Lichess and I find this 
repo. I just found using google and github search.
-- 
As lembranças não são só do passado. Podem ser de agora e até de 
amanhã.
— Serial Experiments Lain
Manoel Vilela,
Discente em Engenharia da Computação,
Universidade Federal do Ceará.

**Comment by KSXGitHub** [comment]
Anyway, this project is no longer maintained. If you are interested, please let me know.
